"""agregar campos presentacion envases a pedidos

Revision ID: 000c6d76cb96
Revises: daa6caefafb4
Create Date: 2026-07-11 16:20:39.864341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000c6d76cb96'
down_revision = 'daa6caefafb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presentacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cantidad_envases', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('litros_por_presentacion', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.drop_index(batch_op.f('idx_pedidos_destinatario'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pedidos_destinatario'), ['destinatario'], unique=False)
        batch_op.drop_column('litros_por_presentacion')
        batch_op.drop_column('cantidad_envases')
        batch_op.drop_column('presentacion')

    # ### end Alembic commands ###
