"""add ajuste parcial fields to pedidos

Revision ID: 1286d3de08f5
Revises: a38876566814
Create Date: 2026-09-13 22:09:23.826096
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1286d3de08f5'
down_revision = 'a38876566814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ajuste_pendiente', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('cantidad_propuesta', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ajuste_nota_fabrica', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('ajuste_nota_fabrica')
        batch_op.drop_column('cantidad_propuesta')
        batch_op.drop_column('ajuste_pendiente')

    # ### end Alembic commands ###
