"""add ajuste parcial fields to pedidos

Revision ID: 1286d3de08f5
Revises: a38876566814
Create Date: 2026-09-13 22:09:23.826096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1286d3de08f5'
down_revision = 'a38876566814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pedidos_destinatario'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pedidos_destinatario'), ['destinatario'], unique=False)

    # ### end Alembic commands ###
