"""init

Revision ID: 220ad3d6dc9e
Revises: 
Create Date: 2026-02-09 03:02:27.931505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220ad3d6dc9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_ruta'), ['ruta'], unique=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pedidos_archivado'))
        batch_op.create_index(batch_op.f('ix_pedidos_archivado'), ['archivado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_archivado'))
        batch_op.create_index(batch_op.f('idx_pedidos_archivado'), ['archivado'], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_ruta'))

    # ### end Alembic commands ###
