"""agregar produccion_diaria y stock_actual en producto

Revision ID: 2541a1eabbd7
Revises: 220ad3d6dc9e
Create Date: 2026-05-26 00:03:44.440461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2541a1eabbd7'
down_revision = '220ad3d6dc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pedidos_producto_id'), ['producto_id'], unique=False)
        batch_op.create_foreign_key('fk_pedidos_producto_id', 'productos', ['producto_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.alter_column('stock_minimo',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('stock_minimo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('stock_actual')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedidos_producto_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pedidos_producto_id'))
        batch_op.drop_column('producto_id')

    # ### end Alembic commands ###
