"""agregar columna procesado a gastos_repartidor

Revision ID: 7a5353ba17e0
Revises: 000c6d76cb96
Create Date: 2026-07-13 01:17:34.865658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5353ba17e0'
down_revision = '000c6d76cb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos_repartidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procesado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos_repartidor', schema=None) as batch_op:
        batch_op.drop_column('procesado')
    # ### end Alembic commands ###
