"""agregar columna ruta a gastos_repartidor

Revision ID: a38876566814
Revises: 7a5353ba17e0
Create Date: 2026-07-13 22:55:23.136401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38876566814'
down_revision = '7a5353ba17e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos_repartidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos_repartidor', schema=None) as batch_op:
        batch_op.drop_column('ruta')
    # ### end Alembic commands ###
