"""add procesado field to pagos_boleta

Revision ID: daa6caefafb4
Revises: c42b055a89fe
Create Date: 2026-07-11 11:56:47.691911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa6caefafb4'
down_revision = 'c42b055a89fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos_boleta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procesado', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_pagos_boleta_procesado'), ['procesado'], unique=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pedidos_destinatario'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pedidos_destinatario'), ['destinatario'], unique=False)

    with op.batch_alter_table('pagos_boleta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_boleta_procesado'))
        batch_op.drop_column('procesado')

    # ### end Alembic commands ###
